/** Predefined exhibitor domain choices. */
export const EXHIBITOR_DOMAINS = [
  'Auteur',
  'Illustrateur',
  'Artisan',
  'Editeur',
  'Association',
  'Alimentation',
  'Bijoux',
  'Tatouage',
  'Bien-etre',
  'Sport',
  'Cosplay',
  'Jeux de societe',
  'Jeux video',
  'Manga / Anime',
  'Comics',
  'BD',
  'Figurines / Maquettes',
  'Papeterie',
  'Textile / Vetements',
  'Accessoires',
  'Decoration',
  'Photographie',
  'Musique',
  'Numerique / Tech',
  'Artiste digital',
  'Ceramique / Poterie',
  'Maroquinerie',
  'Bougie / Encens',
  'Vintage / Retro',
  'Autre',
] as const;

export type ExhibitorDomain = (typeof EXHIBITOR_DOMAINS)[number];
